[colors.primary]
background = "#181818"
foreground = "#f7fae7"

[colors.normal]
black = "#292929"
red = "#DA344D"
green = "#5E5F77"
yellow = "#E4B363"
blue = "#5eb096"
magenta = "#33859D"
cyan = "#6F94B0" # arch logo 
white = "#CCD1DB" 

[colors.bright]
black = "#333333"
red = "#f54747"
green = "#AAABAD"
yellow = "#DBD053"
blue = "#6ac39a"
magenta = "#98D0CF"
cyan = "#C1D6E5" 
white = "#E6E9EF" # text
