#!/usr/bin/env bash
BSPDIR="$HOME/.config/bspwm"
export PATH="${PATH}:$BSPDIR/scripts"
export _JAVA_AWT_WM_NONREPARENTING=1

#---------------------------------------#

BSPWM_FBC='#44BF22'
BSPWM_NBC='#2E3440'
BSPWM_ABC='#B48EAD'
BSPWM_PFC='#A3BE8C'

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

#-----------------------------------------------------------------#

BSPWM_BORDER='0'
BSPWM_GAP='5'
BSPWM_SRATIO='0.50'

bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

#-----------------------------------------------------------------#

default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d '雷' '雷' '雷' '雷'
	done
}
default_workspaces
#-----------------------------------------------------------------#

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

bspc wm --adopt-orphans


killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc
xsettingsd --config="$BSPDIR"/xsettingsd &

if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

sxhkd -c "$BSPDIR"/sxhkdrc &
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
xfce4-power-manager &
# Fix cursor
xsetroot -cursor_name left_ptr
# Restore wallpaper
nitrogen --restore &
# Start mpd
exec mpd &

# Start bspwm scripts
bspcomp &
bspdunst &
bspfloat &
xmodmap .Xmodmap &
bash ~/.config/polybar/launch.sh --forest &
libinput-gestures-setup restart &
xinput --set-prop "ELAN07D2:00 04F3:321A Touchpad" "libinput Accel Speed" 0.25 &
setxkbmap de us
